sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNigKunuDG7HdQVfurK
    access-key-secret: B8rp5ijRAIoj2Db3dhGzTT5XG8sISv
    bucket-name: sky-gong-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  wechat:
    appid: wxc6671f295423b7bf
    secret: 049a943f02f725dc1ce2270534243809